cache:
  manager:
    fallbackToNoOpCache: true
    caffeineCaches:
      - names: [ apikey ]
        allowNullValues: true
        initialCapacity: 100
        maximumSize: 500
        enableRecordStats: false
        expireAfterWriteMinutes: 10
        expireAfterAccessMinutes: 10
        refreshAfterWriteMinutes: 10
      - names: [ tenantByCode ]
        allowNullValues: true
        initialCapacity: 100
        maximumSize: 500
        enableRecordStats: false
        expireAfterWriteMinutes: 10
        expireAfterAccessMinutes: 10
        refreshAfterWriteMinutes: 10
      - names: [ tenantById ]
        allowNullValues: true
        initialCapacity: 100
        maximumSize: 500
        enableRecordStats: false
        expireAfterWriteMinutes: 10
        expireAfterAccessMinutes: 10
        refreshAfterWriteMinutes: 10
      - names: [ userBySubjectId ]
        allowNullValues: true
        initialCapacity: 100
        maximumSize: 500
        enableRecordStats: false
        expireAfterWriteMinutes: 5
        expireAfterAccessMinutes: 5
        refreshAfterWriteMinutes: 5
      - names: [ userAccessTenant ]
        allowNullValues: true
        initialCapacity: 100
        maximumSize: 500
        enableRecordStats: false
        expireAfterWriteMinutes: 5
        expireAfterAccessMinutes: 5
        refreshAfterWriteMinutes: 5
    mapCaches:
      - names: [ cacheB ]
        allowNullValues: true
        storeByValue: true
  apiKey:
    name: apikey
    keyPattern: resolve_$keyhash$:v0
  userBySubjectId:
    name: userBySubjectId
    keyPattern: user_by_subject_$subject$:v0
  tenantByCode:
    name: tenantByCode
    keyPattern: tenant_by_code_$code$:v0
  tenantById:
    name: tenantById
    keyPattern: tenant_by_id_$tenantId$:v0
  userAllowedTenant:
    name: userAccessTenant
    keyPattern: user_access_tenant_$user_id$_$tenant_id$:v0
