spring:
  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USER}
    password: ${RABBIT_PASS}
    ssl:
      enabled: false
queue:
  rabbitmq:
    enable: true
    app-id: ${THE_API_ID}
    durable: null
    queue: null
    exchange: null
    listenerEnabled: true
    publisherEnabled: true
    #TODO
    connection-recovery:
      enable: true
      network-recovery-interval: 5000
      unreachable-recovery-interval: 5000
  task:
    publisher:
      enable: true
      options:
        exchange: null
        forget-me-completed-topic: forgetme.completed
        notify-topic: notification.notify
        tenant-reactivation-topic: tenant.reactivated
        tenant-removal-topic: tenant.remove
        tenant-touch-topic: tenant.touch
        tenant-user-invite-topic: tenant.invite
        what-you-know-about-me-completed-topic: whatyouknowaboutme.completed
        generate-file-topic: generate.file
      rabbitmq:
        enable: true
        interval-seconds: 30
        options:
          retry-threashold: 100
          retry-delay-step-seconds: 300
          max-retry-delay-seconds: 10800
          too-old-to-send-seconds: 604800
          confirm-timeout-seconds: 30
    listener:
      enable: true
      options:
        exchange: null
        user-removal-topic: [ "user.remove" ]
        user-touched-topic: [ "user.touch" ]
      rabbitmq:
        enable: true
        interval-seconds: 30
        options:
          retry-threashold: 100
          retry-delay-step-seconds: 300
          max-retry-delay-seconds: 10800
          too-old-to-send-seconds: 604800