export enum TenantRequestStatus {
	NEW = 'NEW',
	SUBMITTED = 'SUBMITTED',
	IN_PROCESS = 'IN_PROCESS',
	REJECTED = 'REJECTED',
	WITHDRAWN = 'WITHDRAWN',
	APPROVED = 'APPROVED',
	DELETED = 'DELETED',
}
