event-scheduler:
  task:
    processor:
      enable: true
      interval-seconds: 10
      options:
        retry-threshold: 300
        max-retry-delay-seconds: 10800
        too-old-to-handle-seconds: 36000
      overrides: [ ]