indicator-group:
  groups:
    - groupId: BE240B1A-3D3B-4769-BC50-0D2345BFFD0F
      name: data-tree
      code: data-tree
      indicator-codes:
        - ai
        - climate
        - cancer
    - groupId: EA39A344-29C4-4EAC-BF7D-93DAD2CD5550
      name: portofolio
      code: portofolio
      indicator-codes:
        - portofolio