permissions:
  extendedClaims: [ ]
  policies:
    EditNotification:
      roles:
        - ic-sti-superuser
        - tenantadmin
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    DeferredAffiliation:
      roles:
        - ic-sti-superuser
        - tenantadmin
        - ic-sti-guest
        - tenantuser
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    #Datasets
    BrowseDataset:
      roles:
        - ic-sti-superuser
        - user
      clients: [ ]
      allowAnonymous: true
      allowAuthenticated: false
      timeOfDay:
        startingAt: "01:00"
        endingAt: "23:00"
    EditDataset:
      roles:
        - ic-sti-superuser
        - user
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    DeleteDataset:
      roles:
        - ic-sti-superuser
      claims: [ ]
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    #DynamicPages
    BrowseDynamicPage:
      roles:
        - ic-sti-superuser
      clients: [ ]
      allowAnonymous: true
      allowAuthenticated: false
    EditDynamicPage:
      roles:
        - ic-sti-superuser
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    DeleteDynamicPage:
      roles:
        - ic-sti-superuser
      claims: [ ]
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false    
    
    #ExternalToken
    BrowseExternalToken:
      roles:
        - ic-sti-superuser
        - tenantadmin
      clients: [ ]
      allowAnonymous: true
      allowAuthenticated: false
    EditExternalToken:
      roles:
        - ic-sti-superuser
        - tenantadmin
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    CreateChartExternalToken:
        roles:
          - tenantadmin
        clients: [ ]
        allowAnonymous: false
        allowAuthenticated: false
    CreateDashboardExternalToken:
      roles:
        - tenantadmin
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    DeleteExternalToken:
      roles:
        - ic-sti-superuser
        - tenantadmin
      claims: [ ]
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false

    # Indicators
    BrowseIndicator:
      roles:
        - ic-sti-superuser
        - user
        - tenantadmin
      clients: [ ]
      allowAnonymous: true
      allowAuthenticated: false
    EditIndicator:
      roles:
        - ic-sti-superuser
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    ResetIndicator:
      roles:
        - ic-sti-superuser
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    DeleteIndicator:
      roles:
        - ic-sti-superuser
      claims: [ ]
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    BrowseIndicatorReportConfig:
      roles:
        - ic-sti-superuser
      clients: [ ]
      indicator:
        roles:
          - tenantadmin
          - tenantuser
      allowAnonymous: false
      allowAuthenticated: false # Indicators
    # Bookmarks
    BrowseBookmark:
      roles:
        - ic-sti-superuser
      clients: [ ]
      allowAnonymous: true
      allowAuthenticated: false
    EditBookmark:
      roles:
        - ic-sti-superuser
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    DeleteBookmark:
      roles:
        - ic-sti-superuser
      claims: [ ]
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    BrowseIndicatorElastic:
      roles:
        - ic-sti-superuser
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    # DataAccessRequest
    BrowseDataAccessRequest:
      roles:
        - ic-sti-superuser
        - tenantadmin
      clients: [ ]
      allowAnonymous: true
      allowAuthenticated: false
    EditDataAccessRequest:
      roles:
        - ic-sti-superuser
        - tenantadmin
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    CreateDataAccessRequest:
      roles:
        - tenantadmin
        - ic-sti-superuser
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    ApproveDataAccessRequest:
      roles:
        - ic-sti-superuser
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    RejectDataAccessRequest:
      roles:
        - ic-sti-superuser
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    DeleteDataAccessRequest:
      roles:
        - ic-sti-superuser
      claims: [ ]
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    
    # DataGroupRequest
    BrowseDataGroupRequest:
      roles:
        - ic-sti-superuser
        - tenantadmin
      clients: [ ]
      allowAnonymous: true
      allowAuthenticated: false
    EditDataGroupRequest:
      roles:
        - ic-sti-superuser
        - tenantadmin
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    CreateDataGroupRequest:
      roles:
        - tenantadmin
        - ic-sti-superuser
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    DeleteDataGroupRequest:
      roles:
        - ic-sti-superuser
        - tenantadmin
      claims: [ ]
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    # IndicatorAccess
    BrowseIndicatorAccess:
      roles:
        - ic-sti-superuser
        - tenantadmin
      clients: [ ]
      allowAnonymous: true
      allowAuthenticated: false
    EditIndicatorAccess:
      roles:
        - ic-sti-superuser
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    DeleteIndicatorAccess:
      roles:
        - ic-sti-superuser
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false

    # Tenants
    BrowseTenant:
      roles:
        - ic-sti-superuser
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    EditTenant:
      roles:
        - ic-sti-superuser
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    DeleteTenant:
      roles:
        - ic-sti-superuser
      claims: [ ]
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    AllowNoTenant:
      roles:
        - ic-sti-superuser
      claims: [ ]
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false

    # TenantUsers
    BrowseTenantUser:
      roles:
        - ic-sti-superuser
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    EditTenantUser:
      roles:
        - ic-sti-superuser
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    DeleteTenantUser:
      roles:
        - ic-sti-superuser
      claims: [ ]
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false

    # Tenant Requests
    BrowseTenantRequest:
      roles:
        - ic-sti-superuser
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    EditTenantRequest:
      roles:
        - ic-sti-superuser
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    CreateTenantRequest:
      roles:
        - tenantadmin
        - ic-sti-guest
        - ic-sti-superuser
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    ApproveTenantRequest:
      roles:
        - ic-sti-superuser
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    RejectTenantRequest:
      roles:
        - ic-sti-superuser
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    DeleteTenantRequest:
      roles:
        - ic-sti-superuser
      claims: [ ]
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false

    # Users
    BrowseUser:
      roles:
        - ic-sti-superuser
        - tenantadmin
      clients: [ ]
      allowAnonymous: true
      allowAuthenticated: false
    EditUser:
      roles:
        - admin
        - ic-sti-superuser
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    DeleteUser:
      roles:
        - ic-sti-superuser
      claims: [ ]
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false

    # UserInvitations
    BrowseUserInvitation:
      roles:
        - ic-sti-superuser
        - user
      clients: [ ]
      allowAnonymous: true
      allowAuthenticated: false
    EditUserInvitation:
      roles:
        - ic-sti-superuser
        - user
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    DeleteUserInvitation:
      roles:
        - ic-sti-superuser
      claims: [ ]
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false

    # UserSettings
    BrowseUserSettings:
      roles:
        - ic-sti-superuser
      clients: [ ]
      allowAnonymous: true
      allowAuthenticated: false
    EditUserSettings:
      roles:
        - ic-sti-superuser
        - user
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    DeleteUserSettings:
      roles:
        - ic-sti-superuser
      claims: [ ]
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    # BrowseDataTree
    BrowseBrowseDataTreeConfig:
      roles:
        - ic-sti-superuser
        - tenantadmin
        - tenantuser
      clients: [ ]
      allowAnonymous: true
      allowAuthenticated: false
    BrowseBrowseDataTree:
      roles:
        - ic-sti-superuser
        - tenantadmin
        - tenantuser
      clients: [ ]
      allowAnonymous: true
      allowAuthenticated: false    
    # PortofolioConfig
    BrowsePortofolioConfig:
      roles:
        - ic-sti-superuser
        - tenantadmin
        - tenantuser
      clients: [ ]
      allowAnonymous: true
      allowAuthenticated: false
    GetDashboard:
      roles:
        - ic-sti-superuser
        - tenantadmin
        - tenantuser
      clients: [ ]
      allowAnonymous: true
      allowAuthenticated: false
    # UserContactInfo
    BrowseUserContactInfo:
      roles:
        - ic-sti-superuser
      clients: [ ]
      allowAnonymous: true
      allowAuthenticated: false
    EditUserContactInfo:
      roles:
        - ic-sti-superuser
        - user
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    DeleteUserContactInfo:
      roles:
        - ic-sti-superuser
      claims: [ ]
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false

    # Master Items
    BrowseMasterItem:
      roles:
        - ic-sti-superuser
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    EditMasterItem:
      roles:
        - ic-sti-superuser
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    DeleteMasterItem:
      roles:
        - ic-sti-superuser
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false

    # IndicatorPoints
    BrowseIndicatorPoint:
      roles:
        - ic-sti-superuser
      clients: [ ]
      indicator:
        roles:
          - tenantadmin
          - tenantuser
      allowAnonymous: false
      allowAuthenticated: false
    EditIndicatorPoint:
      roles:
        - ic-sti-superuser
      clients: [ ]
      indicator:
        roles:
          - tenantadmin
      allowAnonymous: false
      allowAuthenticated: false
    DeleteIndicatorPoint:
      roles:
        - ic-sti-superuser
      clients: [ ]
      indicator:
        roles:
          - tenantadmin
      allowAnonymous: false
      allowAuthenticated: false
    # Blueprint Request
    BrowseBlueprintRequest:
      roles:
        - ic-sti-superuser
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    CreateBlueprintRequest:
      roles:
        - ic-sti-superuser
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    UpdateBlueprintRequest:
      roles:
        - ic-sti-superuser
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    DeleteBlueprintRequest:
      roles:
        - ic-sti-superuser
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    # Create Blueprint
    CreateBlueprint:
      roles:
        - ic-sti-superuser
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false

    # ViewPage Permissions
    ViewDatasetPage:
      roles:
        - ic-sti-superuser
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    ViewIndicatorPage:
      roles:
        - ic-sti-superuser
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    ViewIndicatorReportsPage:
      roles:
        - tenantadmin
        - tenantuser
        - ic-sti-superuser
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    ViewIndicatorReportsDashboardPage:
      roles:
        - tenantadmin
        - tenantuser
        - ic-sti-superuser
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    ViewMasterItemPage:
      roles:
        - ic-sti-superuser
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    ViewTenantRequestPage:
      roles:
        - ic-sti-superuser
        - tenantadmin
        - ic-sti-guest
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    ViewDataAccessRequestPage:
      roles:
        - ic-sti-superuser
        - tenantadmin
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    ViewMyDataAccessRequestPage:
      roles:
        - ic-sti-superuser
        - tenantadmin
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    ViewTenantPage:
      roles:
        - ic-sti-superuser
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    ViewUsersPage:
      roles:
        - ic-sti-superuser
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    ViewApiClientsPage:
      roles:
        - ic-sti-superuser
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    ViewRoleAssignmentPage:
      roles:
        - ic-sti-superuser
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    ViewAccessTokensPage:
      roles:
        - ic-sti-superuser
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    ViewUserInvitationPage:
      roles:
        - ic-sti-superuser
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    ViewUserProfilePage:
      roles:
        - ic-sti-superuser
        - tenantadmin
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    ViewForgetMeRequestPage:
      roles:
        - ic-sti-superuser
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    ViewWhatYouKnowAboutMeRequestPage:
      roles:
        - ic-sti-superuser
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    ViewTenantConfigurationPage:
      roles:
        - ic-sti-superuser
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    ViewNotificationPage:
      roles:
        - ic-sti-superuser
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    ViewNotificationEventRulePage:
      roles:
        - ic-sti-superuser
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    ViewInAppNotificationPage:
      roles:
        - ic-sti-superuser
        - tenantadmin
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    ViewNotificationTemplatePage:
      roles:
        - ic-sti-superuser
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    ViewBlueprintRequestPage:
      roles:
        - ic-sti-superuser
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    DownloadReport:
      roles:
        - ic-sti-superuser
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    ViewBlueprintTemplatePage:
      roles:
        - ic-sti-superuser
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    ViewDynamicPage:
      roles:
        - ic-sti-superuser
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    ViewExternalTokenPage:
      roles:
        - ic-sti-superuser
        - tenantadmin
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
