tenant:
  multitenancy:
    is-multitenant: true
  interceptor:
    client-claims-prefix: client_
    white-listed-clients: [ ]
    enforce-trusted-tenant: false
    auto-create-tenant-user: true
    white-listed-endpoints: [ '/api/principal/my-tenants',  '/api/principal/me','/api/user/user-settings', '/error', '/api/tenant-request' ]
