error-thesaurus:
  hash-conflict:
    code: 100
    message: there is a hash conflict for the item modified. please reload to get the latest changes
  forbidden:
    code: 101
    message: insufficient rights
  system-error:
    code: 102
    message: an unexpected system error occurred
  missing-tenant:
    code: 103
    message: tenant scope not provided
  invalid-api-key:
    code: 104
    message: provided APIKey not valid
  stale-api-key:
    code: 105
    message: there was a problem authorizing you with your API key. Please try again. Contact the system administrator if the problem persists
  model-validation:
    code: 106
    message: validation error
  sensitive-info:
    code: 107
    message: you are attempting to access sensitive information. please don't do that
  non-person-principal:
    code: 108
    message: the operation is available only to person users
  blocking-consent:
    code: 113
    message: user consents are not sufficient to complete the operation
  single-tenant-configuration-per-type-supported:
    code: 116
    message: a single tenant configuration entry per config type is supported
  incompatible-tenant-configuration-types:
    code: 117
    message: the provided tenant configuration type is incompatible
  missing-totp-token:
    code: 118
    message: totp token not provided
  overlapping-tenant-configuration-notifier-list:
    code: 119
    message: Overlapping Tenant Configuration Notifier List
